-- ============================================================================
-- Sweet & Sour — schema completa (replicata din Á Libretto, cu intariri)
-- Deja aplicat pe proiectul `cjavzdnsebbkiiefigvi` (Sweet and Sour, eu-central-1).
-- Pastrat aici ca sursa de adevar / pentru recrearea proiectului de la zero.
-- ============================================================================

-- ---------------------------------------------------------------- extensii
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists pgcrypto     with schema extensions;
create extension if not exists pg_net       with schema extensions;
create extension if not exists pg_cron;

-- ---------------------------------------------------------------- tabele
create table if not exists public.staff_roles (
  uid uuid primary key references auth.users(id) on delete cascade,
  rol text not null check (rol in ('director','bar','bucatarie','ospatar'))
);

create table if not exists public.comenzi (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  mesa          text    not null,
  produse       jsonb   not null,
  total         numeric not null,
  sectiune      text    not null,
  status        text    default 'noua',
  bon_scos      boolean default false,
  creat_de      text,
  preluat_de    text,
  grup_comanda  uuid,
  comp_motiv    text,
  comp_de       text,
  confirmada_la timestamptz
);

create table if not exists public.contacte_takeaway (
  comanda_id bigint primary key references public.comenzi(id) on delete cascade,
  nume       text,
  telefon    text,
  created_at timestamptz not null default now()
);

create table if not exists public.jurnal_activitate (
  id         bigint generated always as identity primary key,
  created_at timestamptz default now(),
  utilizator text,
  actiune    text,
  comanda_id bigint,
  detalii    jsonb
);

create table if not exists public.stoc_produse (
  id_produs text primary key,
  epuizat   boolean default false
);

create table if not exists public.meniu_produse (
  id_produs      text primary key,
  nume           text    not null,
  descriere      text,
  categorie      text    not null,
  sectiune       text    not null check (sectiune in ('bar','bucatarie')),
  volum          text,
  ingrediente    text[]  not null default '{}',
  alergeni       text[]  not null default '{}',
  pret           numeric not null check (pret >= 0 and pret < 10000),
  pret_variabil  boolean not null default false,
  semnatura      boolean not null default false,
  activ          boolean not null default true,
  ordine         int     not null default 0,
  imagine        text,
  traduceri      jsonb   not null default '{}'::jsonb,
  nume_variante  text[]  not null default '{}',
  actualizat_la  timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  endpoint         text primary key,
  uid              uuid not null references auth.users(id) on delete cascade,
  rol              text not null,
  p256dh           text not null,
  auth_key         text not null,
  user_agent       text,
  creat_la         timestamptz not null default now(),
  ultima_utilizare timestamptz
);

-- ---------------------------------------------------------------- indexuri
create index if not exists idx_comenzi_grup            on public.comenzi (grup_comanda);
create index if not exists idx_comenzi_mesa_confirmada on public.comenzi (mesa, confirmada_la);
create index if not exists idx_comenzi_created_at      on public.comenzi (created_at desc);
create index if not exists idx_jurnal_created_at       on public.jurnal_activitate (created_at desc);
create index if not exists idx_jurnal_actiune          on public.jurnal_activitate (actiune, created_at desc);
create index if not exists idx_meniu_variante        on public.meniu_produse using gin (nume_variante);
create index if not exists idx_push_rol                on public.push_subscriptions (rol);

-- ---------------------------------------------------------------- functii de rol
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = 'public','pg_temp' as $$
  select exists (select 1 from public.staff_roles where uid = (select auth.uid()))
$$;

create or replace function public.current_staff_rol()
returns text language sql stable security definer set search_path = 'public','pg_temp' as $$
  select rol from public.staff_roles where uid = (select auth.uid())
$$;

-- Rolurile se acorda EXCLUSIV din tabela staff_roles, niciodata dupa continutul
-- adresei de email. (In versiunea veche, un cont "director@..." isi lua singur
-- rol de director; era escaladare de privilegii prin simpla alegere a emailului.)

-- ---------------------------------------------------------------- triggere comenzi
create or replace function public.sanitize_comanda_insert()
returns trigger language plpgsql set search_path = 'public','pg_temp' as $$
begin
  if auth.role() = 'anon' or auth.uid() is null then
    NEW.status := 'noua'; NEW.bon_scos := false;
    NEW.comp_motiv := null; NEW.comp_de := null;
    NEW.preluat_de := null; NEW.creat_de := null;
    NEW.confirmada_la := null; NEW.created_at := now();
  else
    if NEW.creat_de is not null then
      NEW.creat_de := (select auth.jwt() ->> 'email');
    end if;
    NEW.created_at := now();
  end if;
  return NEW;
end; $$;

create or replace function public.recalculeaza_total_comanda()
returns trigger language plpgsql security definer set search_path = 'public','pg_temp' as $$
declare
  v_item jsonb; v_items jsonb := '[]'::jsonb; v_total numeric(10,2) := 0;
  v_qty numeric; v_nume text; v_id text; v_pret numeric(10,2);
  v_variabil boolean; v_pret_client numeric; v_gasit boolean;
begin
  if jsonb_typeof(NEW.produse) <> 'array' then
    raise exception 'Campul produse trebuie sa fie o lista.';
  end if;

  for v_item in select * from jsonb_array_elements(NEW.produse) loop
    v_nume := coalesce(v_item ->> 'nume', '');
    v_qty  := coalesce((v_item ->> 'cantitate')::numeric, 0);
    v_id   := nullif(v_item ->> 'id_produs', '');

    -- notele clientului si alertele de ospatar nu sunt produse: raman la 0
    if v_qty <= 0 or v_nume like '📝%' or v_nume like '🔔%'
       or v_nume like '%ALERTĂ OSPĂTAR%' then
      v_items := v_items || jsonb_build_array(v_item || jsonb_build_object('pret_unitar', 0));
      continue;
    end if;

    if v_qty > 50 then
      raise exception 'Cantitate nerezonabila pentru "%": %', v_nume, v_qty;
    end if;

    v_gasit := false;
    if v_id is not null then
      select pret, pret_variabil into v_pret, v_variabil
      from public.meniu_produse where id_produs = v_id;
      v_gasit := found;
    end if;
    if not v_gasit then
      select pret, pret_variabil into v_pret, v_variabil
      from public.meniu_produse
      where lower(btrim(v_nume)) = any (nume_variante) limit 1;
      v_gasit := found;
    end if;
    if not v_gasit then
      raise exception 'Produs inexistent in meniu: "%"', v_nume;
    end if;

    if v_variabil then
      v_pret_client := coalesce((v_item ->> 'pret_unitar')::numeric, 0);
      if v_pret_client < 0 or v_pret_client > 1000 then
        raise exception 'Pret invalid pentru produsul cu pret variabil "%"', v_nume;
      end if;
      v_pret := round(v_pret_client, 2);
    end if;

    v_total := v_total + (v_pret * v_qty);
    v_items := v_items || jsonb_build_array(v_item || jsonb_build_object('pret_unitar', v_pret));
  end loop;

  NEW.produse := v_items;
  NEW.total   := round(v_total, 2);
  return NEW;
end; $$;

create or replace function public.protect_comanda_update()
returns trigger language plpgsql security definer set search_path = 'public','pg_temp' as $$
declare v_rol text; v_uid uuid := (select auth.uid());
begin
  if v_uid is null then return NEW; end if;   -- cron / mentenanta server-side
  select rol into v_rol from public.staff_roles where uid = v_uid;
  if v_rol is null then
    raise exception 'Acces interzis: utilizatorul nu este inregistrat in staff_roles.';
  end if;
  if v_rol <> 'director' then
    if NEW.produse is distinct from OLD.produse
    or NEW.total is distinct from OLD.total
    or NEW.mesa is distinct from OLD.mesa
    or NEW.sectiune is distinct from OLD.sectiune
    or NEW.grup_comanda is distinct from OLD.grup_comanda
    or NEW.created_at is distinct from OLD.created_at then
      raise exception 'Doar directorul poate modifica produsele, totalul sau masa unei comenzi.';
    end if;
  end if;
  if NEW.preluat_de is distinct from OLD.preluat_de and NEW.preluat_de is not null then
    NEW.preluat_de := (select auth.jwt() ->> 'email');
  end if;
  if NEW.comp_de is distinct from OLD.comp_de and NEW.comp_de is not null then
    NEW.comp_de := (select auth.jwt() ->> 'email');
  end if;
  return NEW;
end; $$;

create or replace function public.enforce_bon_scos_bar_only()
returns trigger language plpgsql security definer set search_path = 'public','pg_temp' as $$
declare v_rol text; v_uid uuid := (select auth.uid());
begin
  if NEW.bon_scos is distinct from OLD.bon_scos and v_uid is not null then
    select rol into v_rol from public.staff_roles where uid = v_uid;
    if v_rol is distinct from 'bar' and v_rol is distinct from 'director' then
      raise exception 'Doar personalul de la bar poate confirma bonul.';
    end if;
  end if;
  return NEW;
end; $$;

create or replace function public.split_takeaway_contact()
returns trigger language plpgsql security definer set search_path = 'public','pg_temp' as $$
declare v_rest text; v_nume text; v_tel text;
begin
  if NEW.mesa is not null and NEW.mesa like '%Tk:%' then
    v_rest := btrim(split_part(NEW.mesa, 'Tk:', 2));
    v_nume := btrim(split_part(v_rest, '/', 1));
    v_tel  := btrim(split_part(v_rest, '/', 2));
    insert into public.contacte_takeaway (comanda_id, nume, telefon)
    values (NEW.id, nullif(v_nume,''), nullif(v_tel,''))
    on conflict (comanda_id) do update
      set nume = excluded.nume, telefon = excluded.telefon;
    -- coloana `mesa` ramane fara date personale
    update public.comenzi set mesa = '🥡 La pachet' where id = NEW.id;
  end if;
  return NEW;
end; $$;

create or replace function public.force_jurnal_utilizator()
returns trigger language plpgsql set search_path = 'public','pg_temp' as $$
begin
  if auth.uid() is null then NEW.utilizator := 'client';
  else NEW.utilizator := coalesce((select auth.jwt() ->> 'email'), 'staff');
  end if;
  NEW.created_at := now();
  return NEW;
end; $$;

create or replace function public.push_forteaza_rol()
returns trigger language plpgsql security definer set search_path = 'public','pg_temp' as $$
begin
  select rol into NEW.rol from public.staff_roles where uid = NEW.uid;
  if NEW.rol is null then
    raise exception 'Utilizatorul nu are rol in staff_roles.';
  end if;
  return NEW;
end; $$;

drop trigger if exists trg_sanitize_comanda_insert on public.comenzi;
create trigger trg_sanitize_comanda_insert before insert on public.comenzi
  for each row execute function public.sanitize_comanda_insert();

drop trigger if exists trg_recalculeaza_total on public.comenzi;
create trigger trg_recalculeaza_total before insert on public.comenzi
  for each row execute function public.recalculeaza_total_comanda();

drop trigger if exists trg_protect_comanda_update on public.comenzi;
create trigger trg_protect_comanda_update before update on public.comenzi
  for each row execute function public.protect_comanda_update();

drop trigger if exists trg_enforce_bon_scos on public.comenzi;
create trigger trg_enforce_bon_scos before update on public.comenzi
  for each row execute function public.enforce_bon_scos_bar_only();

drop trigger if exists trg_split_takeaway_contact on public.comenzi;
create trigger trg_split_takeaway_contact after insert on public.comenzi
  for each row execute function public.split_takeaway_contact();

drop trigger if exists trg_force_jurnal_utilizator on public.jurnal_activitate;
create trigger trg_force_jurnal_utilizator before insert on public.jurnal_activitate
  for each row execute function public.force_jurnal_utilizator();

drop trigger if exists trg_push_forteaza_rol on public.push_subscriptions;
create trigger trg_push_forteaza_rol before insert or update on public.push_subscriptions
  for each row execute function public.push_forteaza_rol();

-- ---------------------------------------------------------------- RLS
alter table public.comenzi            enable row level security;
alter table public.contacte_takeaway  enable row level security;
alter table public.jurnal_activitate  enable row level security;
alter table public.staff_roles        enable row level security;
alter table public.stoc_produse       enable row level security;
alter table public.meniu_produse    enable row level security;
alter table public.push_subscriptions enable row level security;

-- comenzi -------------------------------------------------------------------
create policy "insert comanda publica" on public.comenzi
  for insert to anon, authenticated
  with check (
    sectiune in ('bar','bucatarie')
    and total >= 0 and total < 10000
    and jsonb_typeof(produse) = 'array'
    and jsonb_array_length(produse) between 1 and 60
    and length(mesa) <= 120
  );

-- INTARIRE fata de proiectul vechi: acolo, fereastra pentru clientii anonimi era
-- de 12 ore, deci oricine cu link-ul meniului putea citi TOATE comenzile din
-- ultima tura. Aici e taiata la 2 ore, cat sa functioneze urmarirea comenzii
-- proprii, si sunt expuse doar coloanele necesare, printr-o vedere separata.
create policy "select anon recent" on public.comenzi
  for select to anon
  using (created_at > now() - interval '2 hours');

create policy "select staff" on public.comenzi
  for select to authenticated using (public.is_staff());

create policy "update staff" on public.comenzi
  for update to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "delete director sau alerte" on public.comenzi
  for delete to authenticated
  using (
    public.current_staff_rol() = 'director'
    or (public.is_staff() and (produse)::text like '%ALERTĂ OSPĂTAR%')
  );

-- contacte_takeaway ---------------------------------------------------------
-- Nicio politica de INSERT: randurile intra exclusiv prin trigger-ul
-- split_takeaway_contact (security definer). Clientul nu scrie niciodata direct.
create policy "staff citeste contacte takeaway" on public.contacte_takeaway
  for select to authenticated using (public.is_staff());

-- jurnal_activitate ---------------------------------------------------------
-- Fara politici de UPDATE / DELETE: jurnalul de audit este append-only.
create policy "insert feedback client" on public.jurnal_activitate
  for insert to anon
  with check (actiune = 'feedback_client' and length(coalesce(detalii::text,'')) <= 2000);

create policy "insert log staff" on public.jurnal_activitate
  for insert to authenticated
  with check (
    public.is_staff()
    and (actiune not in ('config_mese','setari_busy') or public.current_staff_rol() = 'director')
  );

create policy "select jurnal staff" on public.jurnal_activitate
  for select to authenticated using (public.is_staff());

create policy "select public config" on public.jurnal_activitate
  for select to anon
  using (actiune in ('config_mese','setari_busy','mesa_liberada'));

-- staff_roles ---------------------------------------------------------------
-- Fara politici de scriere: rolurile se acorda DOAR din consola Supabase
-- (service_role). Nici macar directorul nu isi poate schimba rolul din aplicatie.
create policy "staff citeste propriul rol" on public.staff_roles
  for select to authenticated using (uid = (select auth.uid()));

-- stoc_produse --------------------------------------------------------------
create policy "select stoc public" on public.stoc_produse
  for select to anon, authenticated using (true);

create policy "insert stoc staff" on public.stoc_produse
  for insert to authenticated
  with check (public.current_staff_rol() in ('bar','bucatarie','director'));

create policy "update stoc staff" on public.stoc_produse
  for update to authenticated
  using (public.current_staff_rol() in ('bar','bucatarie','director'))
  with check (public.current_staff_rol() in ('bar','bucatarie','director'));

create policy "delete stoc director" on public.stoc_produse
  for delete to authenticated using (public.current_staff_rol() = 'director');

-- meniu_produse -----------------------------------------------------------
create policy "select preturi public" on public.meniu_produse
  for select to anon, authenticated using (true);

create policy "scrie preturi director" on public.meniu_produse
  for all to authenticated
  using (public.current_staff_rol() = 'director')
  with check (public.current_staff_rol() = 'director');

-- push_subscriptions --------------------------------------------------------
create policy "push select propriu" on public.push_subscriptions
  for select to authenticated using (uid = (select auth.uid()));
create policy "push insert propriu" on public.push_subscriptions
  for insert to authenticated with check (uid = (select auth.uid()) and public.is_staff());
create policy "push update propriu" on public.push_subscriptions
  for update to authenticated using (uid = (select auth.uid())) with check (uid = (select auth.uid()));
create policy "push delete propriu" on public.push_subscriptions
  for delete to authenticated using (uid = (select auth.uid()));

-- ---------------------------------------------------------------- GRANTURI
-- INTARIRE fata de proiectul vechi: acolo, `anon` avea din oficiu INSERT,
-- UPDATE, DELETE si TRUNCATE pe toate tabelele. RLS le bloca oricum, dar o
-- politica scrisa gresit ramanea singura aparare. Aici retragem tot si dam
-- inapoi doar minimul necesar. Aparare in adancime.
revoke all on all tables in schema public from anon, authenticated;

grant select                 on public.meniu_produse    to anon, authenticated;
grant select                 on public.stoc_produse       to anon, authenticated;
grant select, insert         on public.comenzi            to anon;
grant select, insert, update, delete on public.comenzi    to authenticated;
grant select, insert         on public.jurnal_activitate  to anon, authenticated;
grant select                 on public.contacte_takeaway  to authenticated;
grant select                 on public.staff_roles        to authenticated;
grant insert, update, delete on public.stoc_produse       to authenticated;
grant insert, update, delete on public.meniu_produse    to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ---------------------------------------------------------------- automatizari
create or replace function public.auto_free_tables()
returns void language plpgsql security definer set search_path = 'public' as $$
declare freed_mesas text[];
begin
  with candidates as (
    select o.mesa, max(o.confirmada_la) as last_confirm
    from comenzi o
    where o.status = 'finalizata' and o.confirmada_la is not null
      and exists (
        select 1 from jsonb_array_elements(o.produse) p
        where p->>'nume' ilike '%ALERT%'
          and (p->>'nume') ~* '(Cash|Card|Numerar|Efectivo|Esp[eè]ces|Carte)'
      )
    group by o.mesa
  ),
  to_free as (
    select c.mesa, c.last_confirm from candidates c
    where now() - c.last_confirm >= interval '15 minutes'
      and not exists (
        select 1 from jurnal_activitate j
        where j.actiune = 'mesa_liberada'
          and j.detalii->>'mesa' = c.mesa
          and j.created_at > c.last_confirm
      )
  ),
  inserted as (
    insert into jurnal_activitate (utilizator, actiune, comanda_id, detalii, created_at)
    select 'sistema', 'mesa_liberada', null,
           jsonb_build_object('mesa', mesa, 'automat', true), now()
    from to_free
    returning detalii->>'mesa' as mesa
  )
  select array_agg(mesa) into freed_mesas from inserted;

  if freed_mesas is not null then
    delete from comenzi o
    where o.mesa = any(freed_mesas)
      and o.status in ('finalizata','noua')
      and exists (
        select 1 from jsonb_array_elements(o.produse) p where p->>'nume' ilike '%ALERT%'
      );
  end if;
end; $$;

-- Inchiderea de la miezul noptii, pe fusul orar al Romaniei.
create or replace function public.curatare_mese_miezul_noptii()
returns void language plpgsql security definer set search_path = 'public' as $$
declare
  data_ro text := to_char((now() at time zone 'utc') at time zone 'Europe/Bucharest', 'YYYY-MM-DD');
  ora_ro  int  := extract(hour from ((now() at time zone 'utc') at time zone 'Europe/Bucharest'));
  deja_rulat boolean; cfg jsonb; zona jsonb; masa jsonb;
begin
  if ora_ro <> 0 then return; end if;

  select exists (
    select 1 from jurnal_activitate
    where actiune = 'curatare_miezul_noptii' and detalii->>'data' = data_ro
  ) into deja_rulat;
  if deja_rulat then return; end if;

  select detalii into cfg from jurnal_activitate
  where actiune = 'config_mese' order by created_at desc limit 1;

  if cfg is not null and cfg ? 'zones' then
    for zona in select jsonb_array_elements(cfg->'zones') loop
      for masa in select jsonb_array_elements(zona->'mese') loop
        insert into jurnal_activitate (utilizator, actiune, comanda_id, detalii)
        values ('sistema', 'mesa_liberada', null,
                jsonb_build_object('mesa', masa->>'numar', 'automat', true,
                                   'motiv', 'inchidere_miezul_noptii'));
      end loop;
    end loop;
  end if;

  insert into jurnal_activitate (utilizator, actiune, comanda_id, detalii)
  values ('sistema', 'curatare_miezul_noptii', null, jsonb_build_object('data', data_ro));
end; $$;

select cron.schedule('auto-free-tables', '* * * * *',
  $$select public.auto_free_tables();$$);

select cron.schedule('curatare-miezul-noptii', '*/10 * * * *',
  $$select public.curatare_mese_miezul_noptii();$$);

-- GDPR: contactele pentru comenzile la pachet dispar dupa 48 de ore.
select cron.schedule('curatare-gdpr-takeaway', '0 3 * * *',
  $$delete from public.contacte_takeaway where created_at < now() - interval '48 hours'$$);

select cron.schedule('curatare-zilnica', '0 3 * * *', $$
  delete from public.comenzi
   where status in ('finalizata','anulata')
     and created_at < now() - interval '2 days';
  delete from public.jurnal_activitate
   where created_at < now() - interval '30 days'
     and actiune not in ('config_mese','setari_busy');
$$);


-- ---------------------------------------------------------------- EXECUTE pe functii
-- Implicit, PUBLIC (deci si `anon`) primeste EXECUTE pe orice functie din schema
-- `public`, iar PostgREST le expune la /rest/v1/rpc/<nume>. Fara asta, oricine
-- putea apela auto_free_tables() la nesfarsit: elibera toate mesele din sala si
-- stergea comenzile-alerta, complet neautentificat.

revoke all on function public.auto_free_tables()             from public, anon, authenticated;
revoke all on function public.curatare_mese_miezul_noptii()  from public, anon, authenticated;

-- Functiile de trigger nu se apeleaza niciodata direct. PostgreSQL nu verifica
-- EXECUTE cand porneste un trigger, deci revocarea nu strica nimic.
revoke all on function public.sanitize_comanda_insert()      from public, anon, authenticated;
revoke all on function public.recalculeaza_total_comanda()   from public, anon, authenticated;
revoke all on function public.protect_comanda_update()       from public, anon, authenticated;
revoke all on function public.enforce_bon_scos_bar_only()    from public, anon, authenticated;
revoke all on function public.split_takeaway_contact()       from public, anon, authenticated;
revoke all on function public.force_jurnal_utilizator()      from public, anon, authenticated;
revoke all on function public.push_forteaza_rol()            from public, anon, authenticated;

-- is_staff() si current_staff_rol() TREBUIE sa ramana apelabile de `authenticated`:
-- politicile RLS se evalueaza cu drepturile apelantului, deci fara EXECUTE s-ar
-- bloca tot dashboard-ul. Nu sunt periculoase — raspund doar despre utilizatorul
-- care intreaba. Le luam insa de la `anon`, care n-are nicio politica ce le foloseste.
revoke all on function public.is_staff()          from public, anon;
revoke all on function public.current_staff_rol() from public, anon;
grant execute on function public.is_staff()          to authenticated;
grant execute on function public.current_staff_rol() to authenticated;

-- Functiile viitoare nu mai primesc EXECUTE automat.
alter default privileges in schema public revoke execute on functions from public, anon;

-- ============================================================================
-- DUPA rulare, mai ai de facut manual (nu se pot automatiza din SQL):
--
-- 1. Authentication -> Providers -> Email: dezactiveaza "Enable sign-ups".
--    Conturile de personal se creeaza doar de tine, din consola.
-- 2. Authentication -> Policies: activeaza "Leaked password protection"
--    si cere parole de minimum 10 caractere.
-- 3. Creeaza conturile de personal, apoi acorda rolurile:
--       insert into public.staff_roles (uid, rol)
--       values ('<uid-din-auth.users>', 'director');
--    Roluri valide: director, bar, bucatarie, ospatar.
-- 4. Adauga produsele din dashboard -> panoul directorului -> Meniu.
-- 5. Pentru notificari push: Edge Functions -> Secrets ->
--    VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT.
--    Apoi Vault -> secret nou `service_role_key`, si ruleaza 03_push.sql.
-- ============================================================================
